### ISSUE TITLE
Update for Cinnamon 3.0

### ISSUE THREAD

**Issue by GLTR87** [dmo60/CoverflowAltTab#57]
CoverflowAltTab does not work in Cinnamon 3.0 (on Arch).

**Comment by p91paul** [comment]
I tested on Cinnamon 3.0, and just adding 3.0 to metadata.json was enough. I see the extension does not support 2.6 and 2.8 though, I will test 2.8 on Debian. I updated the code in this repository; @dmo60 still owns the extension on cinnamon-spices, I have no experience uploading there.

**Comment by p91paul** [comment]
I did need to enable "Always show the animation on the primary desktop" option though, without having a second monitor, which is odd.

**Comment by GLTR87** [comment]
Thanks, I've installed from github. It still does not work on my two Arch installations.
It does however work on Ubuntu 16.04 with Cinnamon 3.0 (embrosyn’s PPA).

**Comment by p91paul** [comment]
What exactly does it happen? the extension can't be installed? Or it can't be added to cinnamon? Or it behaves badly when running? Do you see any error messages?

**Comment by GLTR87** [comment]
OK, I've figured out a few things, I guess I was confused.
1st : its the same in Arch and Ubuntu 16.04, I was wrong in my previous comment.
2nd : there are two ways to get the coverflow alt-tab
       -It looks like it has been integrated in Cinnamon 3.0, go to settings -> windows -> alt-tab
       -Install the extention
3rd : to use coverflow the extension way (allows to speed up the animations), you need to (like you've already mentioned) enable "awlays show the animation on the primary desktop", in the extension configuration, not in the general settings (settings -> windows -> alt-tab) like I was doing.
Everything works, except that I can't get alt-tab on my secondary monitor (because of the enable option), no big deal.
Thanks Paul.
